name: Test GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a test message
        run: echo "GitHub Actions is working!"
